version: '3'
services:
  php:
    build:
        context: .
        dockerfile: ./docker/php/Dockerfile
    volumes:
        - .:/app:cached
        - ./docker/conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:cached
